### ISSUE TITLE
5.8 AgentVersionMajor Edge version

### ISSUE THREAD

**Issue by andreitsibets** [nielsbasjes/yauaa#140]
Since 5.8 the result of AgentVersionMajor for Edge browser is changed.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

yauaa 5.7 returns 16
yauaa 5.8 returns 41

Is it a bug?

Thanks

**Comment by nielsbasjes** [comment]
Yes, it has changed.
It was reported that the '16' was incorrect.

As you can see here https://en.wikipedia.org/wiki/Microsoft_Edge
The version you find in the useragent is actually the version of the engine EdgeHTML
The version of Edge is NOT present in the useragent, but I added a lookup table to fix this.

My code: 
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/MSEdge.yaml#L35

So, yes this changed. 
Yes this is brittle because it needs constant updates.
Yes, it is microsoft making a mess out of things yet again.

**Comment by nielsbasjes** [comment]
I have updated the readme to highlight this change.
