### ISSUE TITLE
Builder not very Scala-friendly

### ISSUE THREAD

**Issue by jbenoit2011** [nielsbasjes/yauaa#147]
I am using this library on a Scala 2.12 app, and I had some hard times to build the User Agent Analyzer with all options I wanted. I think Scala type inference engine is a bit lost with the way type arguments are used in the Builder class.
So I was able to solve this issue by casting explicitly to help Scala compiler:

Solution 1, with `asInstanceOf` method:

```
  val uaa = UserAgentAnalyzer
    .newBuilder
    .withCache(10000)
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .hideMatcherLoadStats
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .withField("DeviceClass")
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .build
    .asInstanceOf[UserAgentAnalyzer]
```

Solution 2, with pattern matching:

```
  val uaa = UserAgentAnalyzer
    .newBuilder
    .withCache(10000) match {
    case b: UserAgentAnalyzerDirectBuilder[_, _] =>
      b.hideMatcherLoadStats match {
        case c: UserAgentAnalyzerDirectBuilder[_, _] =>
          c.withField("DeviceClass") match {
            case d: UserAgentAnalyzerDirectBuilder[_, _] =>
              d.build match {
                case e: UserAgentAnalyzer => e
                case _ => throw new Exception("User-Agent analyzer cannot be built")
              }
            case _ => throw new Exception("User-Agent analyzer cannot be built")
          }
        case _ => throw new Exception("User-Agent analyzer cannot be built")
      }
    case _ => throw new Exception("User-Agent analyzer cannot be built")
  }
```

Do you think this could be added to the README to help further Scala users or it is better to make typing more friendly with Scala?

**Comment by nielsbasjes** [comment]
Thanks for pointing this out.
I'm adding this to the documentation as a start.
By simply reformatting the code of Solution 1 it no longer looks "too strange".

I have zero Scala knowledge, so if you have a suggestion on how I can fix this for the Scala users out there then those suggestions are very welcome.

**Comment by nielsbasjes** [comment]
I put your info at the bottom of this page: https://yauaa.basjes.nl/README-Usage.html

**Comment by jbenoit2011** [comment]
Thanks for adding my snippets to the README.
I think a much better solution would be to rewrite the typing of the Builder classes. I am not a Java expert, but it is pretty much different from what I see in other Java library I use with Scala.
Unfortunately, I have no time to submit a PR at the moment.

**Comment by nielsbasjes** [comment]
I though about this problem and I have chosen not to change the Java code of Yauaa on this aspect.
The reason is that this construct solves the problem of inheriting a Builder from a super class.

In commonly used Java code a Builder can only work on a single specific class.
As soon as you want a class inheritance and 'simply' create an instance for one of the subclasses you will find that the developer needs to duplicate ALL the methods of the other builders and you will see that the access of 'internal' elements becomes an issue.

The way I have done it I can now simply create a subclass of both the target class and the Builder without the need to repeat all methods from the super classes.

See also: https://stackoverflow.com/questions/21086417/builder-pattern-and-inheritance

Thanks for providing the examples on how to handle this in Scala, I think it will really help people.
If you find a better way of doing this I'm happy to include that too in the documentation.

**Comment by nielsbasjes** [comment]
FYI: The construct I'm using is roughly the same as what the Lombok SuperBuilder does.
https://projectlombok.org/features/experimental/SuperBuilder
