### ISSUE TITLE
Thread safe or not?

### ISSUE THREAD

**Issue by mkuthan** [nielsbasjes/yauaa#153]
The documentation states that analyzer is not threadsafe, but it seems that the code is synchronized:
https://github.com/nielsbasjes/yauaa/blob/4673d9f5717e5e9094f41cbb5ecdd3b5fbca3261/analyzer/src/main/java/nl/basjes/parse/useragent/UserAgentAnalyzer.java#L72

Should I synchronize or not when the parse method is called from multiple threads?

**Comment by piwanczak** [comment]
I could be wrong, by my understanding is the lib is single threaded, not nonthreadsafe.
In other words for multithreaded situations you face performance issues due to locks.
vide:
https://yauaa.basjes.nl/README-Usage.html

Shameless plug - I'm currently trying to puzzle out if/how to improve multithreaded performance without significantly increasing the memory footprint. If that's your use case & you have any thoughts on how to do this efficiently I'll be happy to hear your thoughts on this

**Comment by nielsbasjes** [comment]
The documentation should be improved on this point. 
The main engine is internally not thread safe. 
So I have already made sure the parsing entry point is synchronized.
So your application does not need to synchronize, that has already been done.

**Comment by mkuthan** [comment]
@nielsbasjes - thanks for confirmation

@piwanczak - As I understood the parser architecture, most of the memory is utilized by cache. So for multi-threaded applications the cache must be shared but still provide great support for concurrency, e.g Caffeine. In the ideal scenario cache implementation should be pluggable with default implementation based on pure JDK SDK.

**Comment by nielsbasjes** [comment]
I have updated the documentation here https://yauaa.basjes.nl/README-Usage.html
