### ISSUE TITLE
Incorrect robot indentification

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1585]
There are different deviceclass and other attributes values for very similar user agent strings (supposedly from the same user / device):

**The exact useragent**
useragent1: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 H@U2FsdGVkX1+r/nt4kQ63gKBzil053I69tnWN79Y4kSYng9JXRKfY8BOTcV/Ii4NIyb0gOP5Nw34+HQLO8K5FOA==@H Snorlax/2.6.1.2406090117_ios_build_1'
useragent2: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 H@U2FsdGVkX19HCl0Qrm7L0dIvvod+5TZ+I5cHK/VS1cYTxOPFxFZSNe5kQIXtpxPNPjujCZfeKcj1H0GNAZDQ6Q==@H Snorlax/2.6.1.2406090117_ios_build_1'

**Expected/Incorrect fields**
deviceclass1: 'Robot'
deviceclass2: 'Phone'

**Expected behavior**
Not sure why the first one is identified as a robot, looks like the same iPhone to my eye.

**Comment by nielsbasjes** [comment]
The reason the first one is classified as a Robot is because it contains "BOT".
I'll have a closer look later.

**Comment by nielsbasjes** [comment]
What I see here is essentially that both have a part that looks like 

    "H@"+base64("Salted__" + binary)+"@h"
    
I'm going to try to ignore the "H@"+base64+"@h" because such a base64 encoded string can essentially contain just about any string of characters on which rules can trigger.

I've tried to google for this and I have note been able to find any references to this useragent.
    
Any idea what kind of agent this really is?

**Comment by nielsbasjes** [comment]
Fixed by simply ripping that part out before doing the analysis
