### ISSUE TITLE
TikTok webviewapp not recognized

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1603]
**The exact useragent**
useragent1: 'Mozilla/5.0 (Linux; Android 14; SM-S901U Build/UP1A.231005.007; ) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 musical_ly_2023507030 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/musical_ly app_version/35.7.3 ByteLocale/en ByteFullLocale/en Region/US AppId/1233 Spark/1.5.9.5-bugfix AppVersion/35.7.3 BytedanceWebview/d8a21c6'
useragent2: 'Mozilla/5.0 (Linux; Android 14; Infinix X6853 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 trill_350603 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/trill app_version/35.6.3 ByteLocale/ms-MY ByteFullLocale/ms-MY Region/MY AppId/1180 Spark/1.5.9.5-bugfix AppVersion/35.6.3 BytedanceWebview/d8a21c6'

**Expected/Incorrect fields**
webviewappname1: 'Musical_LY_2023507030 Jssdk'
webviewappname2: 'Trill_350603 Jssdk'

**Expected behavior**
Something like TikTok would look more appropriate.

**Comment by nielsbasjes** [comment]
Please double check these with the latest version because I recently added Tiktok detection.

Both of these examples look good to me in v7.28.1 .

https://try.yauaa.basjes.nl/?ua=Mozilla%2F5.0+%28Linux%3B+Android+14%3B+SM-S901U+Build%2FUP1A.231005.007%3B+%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F126.0.6478.134+Mobile+Safari%2F537.36+musical_ly_2023507030+JsSdk%2F1.0+NetType%2FWIFI+Channel%2Fgoogleplay+AppName%2Fmusical_ly+app_version%2F35.7.3+ByteLocale%2Fen+ByteFullLocale%2Fen+Region%2FUS+AppId%2F1233+Spark%2F1.5.9.5-bugfix+AppVersion%2F35.7.3+BytedanceWebview%2Fd8a21c6

https://try.yauaa.basjes.nl/?ua=Mozilla%2F5.0+%28Linux%3B+Android+14%3B+Infinix+X6853+Build%2FUP1A.231005.007%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F126.0.6478.134+Mobile+Safari%2F537.36+trill_350603+JsSdk%2F1.0+NetType%2FWIFI+Channel%2Fgoogleplay+AppName%2Ftrill+app_version%2F35.6.3+ByteLocale%2Fms-MY+ByteFullLocale%2Fms-MY+Region%2FMY+AppId%2F1180+Spark%2F1.5.9.5-bugfix+AppVersion%2F35.6.3+BytedanceWebview%2Fd8a21c6

**Comment by Ivan-N-Kravchenko** [comment]
Right, I used v7.27.
Fixed in v7.28.1 indeed (webviewappname=Unknown, agentname=TikTok).
