### ISSUE TITLE
Relocated shaded dependencies are still transitive.

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#171]
As reported by @kirilkalchev here https://github.com/nielsbasjes/yauaa/pull/170 the downstream users of the Yauaa analyzer still get all the transitive dependencies that have already been shaded/relocated into the jar file.

Problem seems related to https://issues.apache.org/jira/browse/MSHADE-36

We need to have the "dependency-reduced-pom.xml" being used in the final jar instead of what we have now.

**Comment by nielsbasjes** [comment]
This is harder than it seems.
- When building the multi module project the followup modules use the pom.xml in the project.
- When building externally the followup parts use the pom.xml in the shaded jar.

So far: When fixing it for one, I break it for the other.

**Comment by kirilkalchev** [comment]
First of all thanks for the quick response. Java is not my speciality but I will try to summarise what I found. It might save you some time.

I found that the jar command reported wrong dependencies for the analyzer project. Since Java is definitely not my speciality I decided there should be a reason why shade plug doesn't update the pom.xml file for the shaded jar. I tried to find some options in the maven's documentation that  might do the job but it seemed there isn't any.

After a couple of hours reading I narrowed it down to two possible options: 

- Custom shell script that unpacks analyzer jar, replaces pom.xml with dependency reduced one and packs again.
- Shades same dependencies in all child packages as I did in this request for the hive build. 

I decided against the first option because it depends on the building environment(Linux/Windows).

I also saw my pull request fixes only the hive UDF. But this was the only build that I could test. So I decided not to change anything that I couldn't test.

Good luck. I hope this will save you some time.

**Comment by nielsbasjes** [comment]
Thanks for your feedback.

I asked what the right solution is at the maven experts:
https://lists.apache.org/thread.html/9c6779f8e8e57d6eb907095f5daa39a6b204f0d379ac41fc0bf933b6@%3Cusers.maven.apache.org%3E

Seems related to: 
https://issues.apache.org/jira/browse/MSHADE-206

**Comment by nielsbasjes** [comment]
@kirilkalchev I think I fixed it and I would really like you to verify if I did it correctly.
I build it and released a SNAPSHOT version here 
https://oss.sonatype.org/content/repositories/snapshots/nl/basjes/parse/useragent/yauaa-hive/5.12-SNAPSHOT/

The jar file went from 9MB to 4.1MB

Looking forward to your feedback.

**Comment by nielsbasjes** [comment]
I also wrote documentation on the current solution
https://yauaa.basjes.nl/NOTES-shading-dependencies.html

**Comment by kirilkalchev** [comment]
I tested the snapshot. It worked on my hive setup. I also checked the new jar metadata. Everything there looked good.

**Comment by nielsbasjes** [comment]
Thanks for testing!
P.S. I've put up a fix in the maven-shade-plugin for a part of this problem:
https://github.com/apache/maven-shade-plugin/pull/25

**Comment by nielsbasjes** [comment]
Yesterday I released v5.12 that includes this fix.
