### ISSUE TITLE
Unknown Webview App for Facebook iOS

### ISSUE THREAD

**Issue by buck06191** [nielsbasjes/yauaa#179]
**The exact useragent**
useragent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/13.1.3;FBSS/2;FBID/phone;FBLC/en_GB;FBOP/5;FBCR/EE]'

**Expected/Incorrect fields**
Webview App Name: 'Unknown Webview App'

Should be

Webview App Name: 'Facebook App for iOS'

**Expected behavior**
Should return a correct Webview App Name

**Comment by nielsbasjes** [comment]
Thanks for this report.
Turns out I ran into a different example of the exact same problem last week.

Here the Facebook app name (FBAN) is mentioned without a version (FBAV) and thus the rules I originally had failed to match. I changed this only a few days ago and this also fixes the example you provided.

I've deployed a new version of the test webapp so you can verify https://try.yauaa.basjes.nl/

**Comment by buck06191** [comment]
Tested that out just now and that works great! When will the package be updated to reflect this so that we can update our code?

**Comment by nielsbasjes** [comment]
I've been working on rewriting some of the rules to get the memory footprint down (it got too big).
As a nice side effect the startup time also got a bit faster.
Currently working on creating a release.

**Comment by nielsbasjes** [comment]
Released. 
Version 5.13 is on it's way towards Maven central.
