### ISSUE TITLE
Build/test failures when building project 

### ISSUE THREAD

**Issue by djhworld** [nielsbasjes/yauaa#192]
**Describe the bug**

We are trying to build the project, but every time the build fails due to test failures 

```
[ERROR] Failures:
[ERROR]   TestPredefinedBrowsers.validateAllPredefinedBrowsers:48 expected: <true> but was: <false>
[ERROR]   TestPredefinedBrowsers.validate_DeviceClass_AgentNameVersionMajor:72->validateAllPredefinedBrowsersMultipleFields:64 expected: <true> but was: <false>
[ERROR]   TestPredefinedBrowsers.validate_DeviceClass_AgentNameVersionMajor_OperatingSystemVersionBuild:81->validateAllPredefinedBrowsersMultipleFields:64 expected: <true> but was: <false>
[ERROR]   TestJavaSerialization>AbstractSerializationTest.serializeAndDeserializeFastRealTests:51->AbstractSerializationTest.serializeAndDeserializeUAA:136 Tests AFTER serialization failed ==> expected: <true> but was: <false>
[ERROR]   TestJavaSerialization>AbstractSerializationTest.serializeAndDeserializeFullNOTestsBeforeRealTests:41->AbstractSerializationTest.serializeAndDeserializeUAA:136 Tests AFTER serialization failed ==> expected: <true> but was: <false>
[ERROR]   TestJavaSerialization>AbstractSerializationTest.serializeAndDeserializeFullTestsBeforeRealTests:46->AbstractSerializationTest.serializeAndDeserializeUAA:99 Tests BEFORE serialization failed ==> expected: <true> but was: <false>
[ERROR]   TestKryoSerialization>AbstractSerializationTest.serializeAndDeserializeFastRealTests:51->AbstractSerializationTest.serializeAndDeserializeUAA:136 Tests AFTER serialization failed ==> expected: <true> but was: <false>
[ERROR]   TestKryoSerialization>AbstractSerializationTest.serializeAndDeserializeFullNOTestsBeforeRealTests:41->AbstractSerializationTest.serializeAndDeserializeUAA:136 Tests AFTER serialization failed ==> expected: <true> but was: <false>
[ERROR]   TestKryoSerialization>AbstractSerializationTest.serializeAndDeserializeFullTestsBeforeRealTests:46->AbstractSerializationTest.serializeAndDeserializeUAA:99 Tests BEFORE serialization failed ==> expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 183, Failures: 9, Errors: 0, Skipped: 4
```

**Component where the bug happens**

[x] Core analyzer

**To Reproduce**

```
git clone git@github.com:nielsbasjes/yauaa.git
git checkout tags/v5.14.1
mvn clean package
```

**Expected behavior**

Build completes successfully

**Screenshots**

**Additional context**

java version

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

maven version

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
```

operating system

```
osx 10.12
```

**Comment by djhworld** [comment]
Some additional content from the log output

```
12:30:12,983 [INFO ] AbstractUserAgentAnalyzerTester         :  467: Location of failed test.(BrokenUseragents.yaml:2457)
[ERROR] Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 3.653 s <<< FAILURE! - in nl.basjes.parse.useragent.TestPredefinedBrowsers
[ERROR] validateAllPredefinedBrowsers  Time elapsed: 1.322 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at nl.basjes.parse.useragent.TestPredefinedBrowsers.validateAllPredefinedBrowsers(TestPredefinedBrowsers.java:48)

[ERROR] validate_DeviceClass_AgentNameVersionMajor_OperatingSystemVersionBuild  Time elapsed: 1.011 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at nl.basjes.parse.useragent.TestPredefinedBrowsers.validateAllPredefinedBrowsersMultipleFields(TestPredefinedBrowsers.java:64)
	at nl.basjes.parse.useragent.TestPredefinedBrowsers.validate_DeviceClass_AgentNameVersionMajor_OperatingSystemVersionBuild(TestPredefinedBrowsers.java:81)

[ERROR] validate_DeviceClass_AgentNameVersionMajor  Time elapsed: 0.95 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at nl.basjes.parse.useragent.TestPredefinedBrowsers.validateAllPredefinedBrowsersMultipleFields(TestPredefinedBrowsers.java:64)
	at nl.basjes.parse.useragent.TestPredefinedBrowsers.validate_DeviceClass_AgentNameVersionMajor(TestPredefinedBrowsers.java:72)
```

**Comment by nielsbasjes** [comment]
This tag was successfully built and tested by TravisCI when I released it: https://travis-ci.org/nielsbasjes/yauaa/builds/623743656

So there must be an incompatibility between your environment and my code.

So either there is a problem in your build environment or one of my scripts simply doesn't work right on a Mac.

Do you see any other errors during the build of the analyzer?

I'm especially looking for problems during the build phase of the analyzer (i.e. what happens before it starts to run the tests)

Do note that the codebase has a script ./start-docker.sh that is intended to create a working build environment using Docker.

**Comment by djhworld** [comment]
It's difficult to see other errors/they might get lost of in the noise.

I've attached the output of `mvn clean package` if that helps

[mvn-output.log](https://github.com/nielsbasjes/yauaa/files/4070753/mvn-output.log)

I tried the docker container on OSX but the maven build failed writing or reading from `.gitconfig` ('permission denied`) so there might be something weird going on with the user management/permissions when mounting the directory - I'm running Docker for Mac. 

However I did spin up CentOS7 in a VM, launch the docker container and was successfully able to build the project via that route so it's a workaround if a little cumbersome

**Comment by nielsbasjes** [comment]
Thanks, this helps a lot.

As I suspected this test failed because the rules from one of the generated files did not trigger. 

In this case the missing rule should have been present in /Users/daniel/workspace/yauaa/analyzer/src/main/resources/UserAgents/OperatingSystemDeviceNames.yaml

When I look at your logfile I see

Loading  315 (dropped    0) matchers from OperatingSystemDeviceNames.yaml

When I run it myself on this version

Loading  405 (dropped    0) matchers from OperatingSystemDeviceNames.yaml

```
[  nbasjes:~/workspace/yauaa {(v5.14.1)} ]
$ fgrep 'matcher:' analyzer/src/main/resources/UserAgents/OperatingSystemDeviceNames.yaml  | wc -l
405
```
So it seems a significant set of the rules has not been generated correctly on your system (causing the build to fail).

At this point I suspect the script that generates this file ( analyzer/src/main/code-gen/UserAgents/OSDeviceNames/Generate.sh ) has a bug that does not allow it to run correctly on a Mac.

Can you please attach this file as it was generated on your system so I can check what is happening?

Thanks.

**Comment by djhworld** [comment]
Sure, find attached (gzipped as github won't allow yaml)


[OperatingSystemDeviceNames.yaml.gz](https://github.com/nielsbasjes/yauaa/files/4072151/OperatingSystemDeviceNames.yaml.gz)

What also might be of interest is the output from the mvn command prints the following to stderr - which might be coming from that shell script

{code}
line 1:24 extraneous input '"Safari"' expecting <EOF>
line 1:2 no viable alternative at input '${123'
line 1:0 mismatched input '=' expecting {'IsNull', 'Concat', 'NormalizeBrand', 'CleanVersion', 'LookUp', 'LookUpContains', 'IsInLookUpContains', 'LookUpPrefix', 'IsInLookUpPrefix', 'agent', VALUE, '@'}
line 1:0 mismatched input '=' expecting {'Concat', 'NormalizeBrand', 'CleanVersion', 'LookUp', 'LookUpContains', 'IsInLookUpContains', 'LookUpPrefix', 'IsInLookUpPrefix', 'agent', VALUE, '@'}
line 1:0 mismatched input '=' expecting {'Concat', 'NormalizeBrand', 'CleanVersion', 'LookUp', 'LookUpContains', 'IsInLookUpContains', 'LookUpPrefix', 'IsInLookUpPrefix', 'agent', VALUE, '@'}
{code}

**Comment by nielsbasjes** [comment]
The file you uploaded confirms part of the generator script does not work as intended in your machine.

Some code blocks are completely missing.
The problem lies most likely in [this line](https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/code-gen/UserAgents/OSDeviceNames/Generate.sh#L72) that generates a series of 'x' in the variable `ospatternWords` which essentially count the words and then use that in a [case statement](https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/code-gen/UserAgents/OSDeviceNames/Generate.sh#L113) to determine which code block must be generated.

For some reason on your machine it doesn't result in the expected output and as a consequence none of the possible blocks are generated.

Because I do not have a Mac (just Linux) I may be able to figure it out if you could check what this code does on your machine.

If you do something like this the output should reveal a lot

```
cd analyzer/src/main/code-gen/UserAgents/OSDeviceNames
touch OperatingSystemDeviceNames.csv;
bash -x ./Generate.sh  > Generate.log 2>&1
```

On my machine the last entry generated by this code shows this at the part where the value is determined:
```
++ echo 'UNIX BSD/SYSV system'
++ sed 's@[^ ]\+@x@g;s@ @@g'
+ ospatternWords=xxx
```
and then later
```
+ case ${ospatternWords} in
+ echo '
# Three words
```

Thanks for helping out on this.

**Comment by nielsbasjes** [comment]
I made some changes to the scripting yesterday (master branch) and rewrote the problematic expression.
Can you please check if it now works on your environment.

**Comment by djhworld** [comment]
Hi @nielsbasjes - building the master branch has fixed the problem 👍 

Cheers

**Comment by nielsbasjes** [comment]
Thanks for your help.
