### ISSUE TITLE
thread blocked

### ISSUE THREAD

**Issue by MayDaycwxiong** [nielsbasjes/yauaa#385]
**Describe the bug**
**Single instance multithreaded get operation to obtain lock**
Because the initialization step of the complete UserAgentAnalyzer (all fields) usually takes 2-5 seconds, we make the Useragentanalyzer a static member of the class, and then use uaa.parse("Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11"); After parsing UA, we found that many threads are in blocked state, and threads are blocked in nl.basjes.parse.useragent.AbstractUserAgentAnalyzer#parse. We use nl.basjes.parse.useragent.AbstractUserAgentAnalyzer#parseCache, which is a scenario where the operation of parseCache.get (userAgentString) is much larger than that of parseCache.put (userAgentString, cachedValue).
we use it in our code(We are using version 5.15)
![image](https://user-images.githubusercontent.com/37573713/145318658-261a34c5-5d11-4c2a-9018-7b8b3f9da1e1.png)

the thread stack information
![image](https://user-images.githubusercontent.com/37573713/145322750-417cb5d0-5571-43ef-8c85-3531aaf0c494.png)

**Component where the bug happens**
![image](https://user-images.githubusercontent.com/37573713/145183595-049fecb1-d92e-41cb-adfc-ca0ca5ffe27c.png)
**To Reproduce**
Steps or code fragment to reproduce the behavior:
1. '...'
2. '...'

**Expected behavior**
If there is a cache in nl.basjes.parse.useragent.AbstractUserAgentAnalyzer#parseCache, the multi-threaded parseCache.get (userAgentString) operation does not need to obtain the object lock, but only the parseCache.put(userAgentString, cachedValue) operation needs to obtain the lock to reduce the granularity of the lock.
![image](https://user-images.githubusercontent.com/37573713/145216738-4e934305-b031-4d62-91ec-0a76d236b5b7.png)

**Screenshots**

**Additional context**
What is the ultimate solution for our business
1. Source code direction: nl.basjes.parse.useragent.AbstractUserAgentAnalyzer#parse method really needs to add locks in line 101 else (method area lock -- > code block lock, reduce the granularity of locks, let all initialized UA get directly from the cache, and reduce the number of threads locked).
2. Business level: we can maintain a UA list somewhere, get the UA when the program starts, and then parse the UA and put it into the cache to reduce the probability of UA conversion and locking in the program.

**Comment by nielsbasjes** [comment]
I rechecked this part of the code.

I'm using an LRU because this will make the cache have an automatically managed expiry of values that are no longer required. So if a value is not requested for a while it will be removed automatically.

You say:

    If there is a cache in nl.basjes.parse.useragent.AbstractUserAgentAnalyzer#parseCache,
    the multi-threaded parseCache.get (userAgentString) operation does not need to obtain 
    the object lock,

Long time ago I chose to use the LRU cache implementation from Apache commons (org.apache.commons.collections4.map.LRUMap) which has been documented as

    * <strong>Note that LRUMap is not synchronized and is not thread-safe.</strong>
    * If you wish to use this map from multiple threads concurrently, you must use
    * appropriate synchronization.

A key thing here is that an LRU (in general) changes the internal data structures on a get operation to adjust the ordering of the entries. So this does require synchronization on the get.

Do you have an idea on how to improve the caching?

**Comment by nielsbasjes** [comment]
Note that instead of 
  `UserAgentAnalyzer.newBuilder() ... .build();`
you can also do
  `UserAgentAnalyzerDirect.newBuilder() ... .build();`
This will give you an instance that does not have any caching at all.

You can use this version and simply wrap it in the caching construct you prefer.

**Comment by nielsbasjes** [comment]
I'll have a look if I can split the locking up into multiple parts and if this has a performance gain.

**Comment by nielsbasjes** [comment]
I have created a new test that runs getting a cached value (many times) and at the same moment run all ~4000 not yet cached testcases.

Running just the single testcase takes ~24ns each on my machine.
Adding the ~4000 noncached testcases to the mix makes that ~174ns each.

git 
Now getting the cached value takes ~28ns which is a lot faster than the 174ns it was before.

So thanks for making me aware of this!

I have built this latest version and pushed a testbuild (version  6.4-SNAPSHOT ) to this maven repo: https://yauaa.basjes.nl/using/#snapshots

```
<repositories>
  <repository>
    <id>sonatype-oss-snapshots</id>
    <name>Sonatype OSS Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases><enabled>false</enabled></releases>
    <snapshots><enabled>true</enabled></snapshots>
  </repository>
</repositories>
```


Can you please check if this solves your problem?

**Comment by chaoyangnz** [comment]
Yep, same issue, this library largely affect the server startup. we are intialising UserAgentAnalyzer as a static field in our Filter. it takes 3 seconds.

**Comment by nielsbasjes** [comment]
Ok, I'm stuck here as I do not see any further possible improvements in my code right now.

The options I can think of right now:

1. Accept the performance you have right now.
2. Create a set of instances in your application, thus spreading the load over multiple. Yet this will have a big memory footprint.
3. Give me a suggestion on how I can fix this caching for you scenario.
4. You build your own caching layer instead of using the one I provided: i.e. use `UserAgentAnalyzerDirect.newBuilder() ... .build();` which does not include caching.

If you have other suggestions then please let me know.

**Comment by nielsbasjes** [comment]
5. You create a single instance of the Analyzer yet you have a separate cache for each thread.

**Comment by nielsbasjes** [comment]
Hi,
With Yauaa version 6.7 you can now inject your own caching implementation easily: https://yauaa.basjes.nl/using/#custom-caching-implementation

In addition I had a look if there are any LRU type caches that may fix the problem for you. I was not able to find anything, so I slapped something together as an experiment: 
https://github.com/nielsbasjes/SLRUMap

Can you check if something like this solves the problem in your scenario?

**Comment by ben-manes** [comment]
@nielsbasjes I saw your tweet and gave your SLRU cache a spin in a [jmh benchmark](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/GetPutBenchmark.java) (see this hacky [patch](https://github.com/nielsbasjes/yauaa/files/7878391/slru.patch.txt)). Thanks to using lock striping it has 4.5x  read throughput compared to a fully synchronized LRU. Unfortunately this won't scale much further because while the hash entries are evenly distributed, the access pattern is highly skewed to favor a few entries (Zipfian). This means that segments holding hot entries have much higher lock contention. If all threads focused on a single hot entry then the performance wouldn't be any better because of the exclusive lock guarding it.

If you're interested in caching then you might enjoy my articles on how I tackled the problem ([part 1](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html), [part 2](http://highscalability.com/blog/2019/2/25/design-of-a-modern-cachepart-deux.html), [slides](https://docs.google.com/presentation/d/1NlDxyXsUG1qlVHMl4vsUUBQfAJ2c2NsFPNPr2qymIBs)). There are other approaches than what I took, and you might play with your own ideas to discover new ones. For mine, the concurrency model was explored in my older [ConcurrentLinkedHashMap](https://github.com/ben-manes/concurrentlinkedhashmap) project and that is a simpler read if you feel inclined. Anyway, if it's something you'd find fun exploring then feel welcome to borrow my benchmarks, simulator, etc. to bootstrap from. I found caching to be a fun hobby project, so I am happy to others playing with it too.

**Comment by nielsbasjes** [comment]
@ben-manes Thanks a lot for giving me this information. Your caching implementation looks a lot better than what I have been able to find so far.

@MayDaycwxiong @chaoyangnz 
With Yauaa 6.7 you can try if the caching system created by @ben-manes ( https://github.com/ben-manes/caffeine ) works better in your situation.

The simplest way for you to do this looks something like this:
```
UserAgentAnalyzer uaa = UserAgentAnalyzer
    .newBuilder()
    .withCacheInstantiator((CacheInstantiator) cacheSize -> 
         Caffeine.newBuilder().maximumSize(cacheSize).<String, ImmutableUserAgent>build().asMap())
    .withCache(10_000)
    .hideMatcherLoadStats()
    .build();
```

I'm curious to hear if this helped in your context.

**Comment by MayDaycwxiong** [comment]
> @ben-manes Thanks a lot for giving me this information. Your caching implementation looks a lot better than what I have been able to find so far.
> 
> @MayDaycwxiong @chaoyangnz With Yauaa 6.7 you can try if the caching system created by @ben-manes ( https://github.com/ben-manes/caffeine ) works better in your situation.
> 
> The simplest way for you to do this looks something like this:
> 
> ```
> UserAgentAnalyzer uaa = UserAgentAnalyzer
>     .newBuilder()
>     .withCacheInstantiator((CacheInstantiator) cacheSize -> 
>          Caffeine.newBuilder().maximumSize(cacheSize).<String, ImmutableUserAgent>build().asMap())
>     .withCache(10_000)
>     .hideMatcherLoadStats()
>     .build();
> ```
> 
> I'm curious to hear if this helped in your context.

I've been trying to reply to you recently, but I'm a little busy. I'm sorry
Thank you for your reply. Our project has used caffeine to implement UA caching before christmas, and has performed well in the production environment. The following is the solution we sorted out at that time. Now share it
REASON
At present, the UA parsing function in our project uses the collections in the UA parsing library yauaa Collections.synchronizedMap(new LRUMap(this.cacheSize)) → adjusted in the yauaa version 6.4 LRUMap was used before 6.4, which is passed in nl.basjes.parse.useragent add the synchronized keyword to the AbstractUserAgentAnalyzer#parse method to ensure atomicity.
The synchronized method before the yauaa version 6.4 ensures atomicity. When reading and writing UA, you need to obtain the object lock of static UserAgentAnalyzer uaa, which will cause many threads to be blocked in the concurrency scenario (the peak value of single machine QPS of HTTP interface is about 38).
In the yauaa 6.4 version ,using the improvement of Collections.synchronizedMap(new LRUMap(this.cacheSize)), you need to get java.util.Collections.SynchronizedMap#mutex when UA reads util. Collections. Although the  SynchronizedMap#mutex lock effectively reduces the granularity of the lock compared with the version before 6.4, it will still be blocked, and the object lock of the static UserAgentAnalyzer uaa still needs to be obtained in the process of UA parsing, which will also lead to multi-threaded blocking in concurrent scenarios (the peak value of single machine QPS of HTTP interface is about 38).
TECHNOLOGY SELECTION
Principle: you do not need to obtain locks when reading from UA, but directly read from the cache. You only need to obtain locks when writing from UA
The difference in reading and writing speed between using LRUMap for data caching and  caffeine for data caching 
<!DOCTYPE html>

cache | 100qps parallel writing | 100qps parallel reading | 100qps concurrent writing | 100qps concurrent reading | 50 ua, each ua has 50 writing qps | 50 ua, each ua has 50 reading qps
-- | -- | -- | -- | -- | -- | --
UA-LRU | The longest time is 4325 ms, the shortest time is 3638 ms, and the average time is 3974 ms | The longest time is 4 ms, the shortest time is 0 ms, and the average time is 0 ms | The longest time is 3844 ms, the shortest time is 3609 ms, and the average time is 3729 ms | The longest time is 2 ms, the shortest time is 0 ms, and the average time is 0 ms | The longest time is 9999 ms, the shortest time is 4144 ms, and the average time is 7751 ms | The longest time is 133 ms, the shortest time is 0 ms, and the average time is 32 ms
caffeine | The longest time is 3547 ms, the shortest time is 3515 ms, and the average time is 3527 ms | The longest time is 2 ms, the shortest time is 0 ms, and the average time is 0 ms | The longest time is 3432 ms, the shortest time is 3411 ms, and the average time is 3421 ms | The longest time is 2 ms, the shortest time is 0 ms, and the average time is 0 ms | The longest time is 5496 ms, the shortest time is 4223 ms, and the average time is 5111 ms | The longest time is 121 ms, the shortest time is 0 ms, and the average time is 28 ms

COMPARISON CONCLUSION
Using  caffeine for data caching can reduce UA read / write RT, and caffeine for data caching is better than implemented in the latest yauaa version 6.4 Collections.synchronizedMap(new LRUMap(this.cacheSize)) to ensure atomicity. You don't need to get  java.util.Collections.SynchronizedMap#mutex  lock when reading and writing  which can effectively alleviate the problem of thread blocking; The static UserAgentAnalyzer uaa object needs to be obtained only during UA parsing

**Comment by ben-manes** [comment]
If Caffeine helped, that's wonderful to hear! 🙂 

@nielsbasjes You might consider changing your cache lookup to avoid racy loads on a miss. The get-load-put idiom allows for multiple threads to observe a miss and do redundant work. This is known as a cache stampede and it is easily mitigated using `Map.computeIfAbsent`. For a concurrent cache like Caffeine this is ideal, but for a synchronized Map it degrades as the computation is performed under the map's lock rather than per-entry. In that case one can reinvent the concept using striped locking, but obviously it's much messier than using a `ConcurrentMap` instead.

https://github.com/nielsbasjes/yauaa/blob/3cddcb89a7c8ec01a0af733c5ea243b19312d237/analyzer/src/main/java/nl/basjes/parse/useragent/AbstractUserAgentAnalyzer.java#L161-L169

**Comment by nielsbasjes** [comment]
@ben-manes I have made several changes and incorporated your point to use the computeIfAbsent.
Seeing that your cache works a lot better than the simple LRU I have been using I have decided to make ik the new default (with still the option to override that).

I ran into a problem for which I made an issue in your project: https://github.com/ben-manes/caffeine/issues/652

Thanks for helping out!
