### ISSUE TITLE
Mac OS X major version

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#569]
The major version of Mac OS X is given as 10 for the entire twenty years of its existence, from 10.0 in 2001 to 10.15 in 2019.
The real major version is comprised of the first two numbers as in `10.7` or `10.15`.

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML; like Gecko) Version/15.4 Safari/605.1.15'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Apple Macintosh'
      DeviceBrand  : 'Apple'
      DeviceCpu  : 'Intel'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Mac OS X'
      OperatingSystemVersion  : '10.15.6'
      OperatingSystemVersionMajor  : '10.15'
      OperatingSystemNameVersion  : 'Mac OS X 10.15.6'
      OperatingSystemNameVersionMajor  : 'Mac OS X 10.15'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'AppleWebKit'
      LayoutEngineVersion  : '605.1.15'
      LayoutEngineVersionMajor  : '605'
      LayoutEngineNameVersion  : 'AppleWebKit 605.1.15'
      LayoutEngineNameVersionMajor  : 'AppleWebKit 605'
      AgentClass  : 'Browser'
      AgentName  : 'Safari'
      AgentVersion  : '15.4'
      AgentVersionMajor  : '15'
      AgentNameVersion  : 'Safari 15.4'
      AgentNameVersionMajor  : 'Safari 15'

```

**Comment by FrancoisDevemy5** [comment]
Also, but of less importance, the official name is now macOS since 10.12.
Between 10.8 and 10.11 it was just OS X, before that Mac OS X.
Not sure if we should have one name or multiple names for all the versions.

**Comment by nielsbasjes** [comment]
So there are two valid points you make here:

1) The marketing naming of Mac OS X has changed over time.
   I'm choosing right now in this case to keep the reporting name (i.e. what Yauaa makes of it) stable as this makes reporting on all of this easier for people. Also if people have attached business rules on top of this these will remain working.

2) The "real" major version for Mac OS is "10.15" instead of just "10".
   Yes, I have to think about that one. The current implementation just takes the `OperatingSystemVersion` and takes the first number to get to the MajorVersion.
   Also: this is why I also have the `OperatingSystemVersion: '10.15.6'` which allows anyone to fiddle with the resulting data as they see fit for their purpose.

**Comment by nielsbasjes** [comment]
Looking at the various site I came to the conclusion that with macOS 11 they stopped using this scheme. So for the 10.x range I now have 2 parts for the Major version (i.e. '10.15') and for all other versions and all other browsers I have only 1 part.

Same as in the timeline image on Wikipedia is shown.

**Comment by nielsbasjes** [comment]
Fixed:
https://try.yauaa.basjes.nl/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_6%29+AppleWebKit%2F605.1.15+%28KHTML%3B+like+Gecko%29+Version%2F15.4+Safari%2F605.1.15
