### ISSUE TITLE
Google web light not being detected as robot

### ISSUE THREAD

**Issue by OranShuster** [nielsbasjes/yauaa#673]
**The exact useragent**
Taken from https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers
useragent: `Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19`

**Expected/Incorrect fields**
DeviceClass: `Robot`/`Robot Mobile`

**Expected behavior**
While the device brand and name is detected correctly, this should be classified as some kind of a robot

**Comment by nielsbasjes** [comment]
What I understood from https://developers.google.com/search/docs/advanced/mobile/web-light is that this is in reality a kind of proxy for users on mobile devices that is intended to reduce the data that needs to be transported.
So all requests are really a "live" user behind a Google operated proxy.
So that is why it is currently classified as DeviceClass: 'Anonymized'

Can you explain why you would choose to report these are "Robot" instead?

**Comment by OranShuster** [comment]
> What I understood from https://developers.google.com/search/docs/advanced/mobile/web-light is that this is in reality a kind of proxy for users on mobile devices that is intended to reduce the data that needs to be transported. So all requests are really a "live" user behind a Google operated proxy. So that is why it is currently classified as DeviceClass: 'Anonymized'
> 
> Can you explain why you would choose to report these are "Robot" instead?

When i read it initially I thought it is kind of a crawl-transcode-cache type.
Reading it again it does look like it will just proxy the request and cache some static bits

So clearly shouldn't be classified as Robot*. And while its not the intended use of web light it does fit the Anonymized class
