### ISSUE TITLE
Mobile Device Model --OPPO cant find brand

### ISSUE THREAD

**Issue by caotao94** [nielsbasjes/yauaa#798]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 11; PCHM10 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.181 Mobile Safari/537.36 JsSdk/2 NewsArticle/1.6.2 GoldBrowser/1.6.2 NetType/wifi TTWebView/0881130043405'

**Expected/Incorrect fields**
"DeviceBrand": "Unknown",
"DeviceName": "PCHM10"
...

**Expected behavior**
I use python package user-agents output:
"brand":"Oppo"
"model":"PCHM10"

**Additional information**
python exp:

`
from user_agents import parse

def main():
            user_agent = "Mozilla/5.0 (Linux; Android 11; PCHM10 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.181 Mobile Safari/537.36 JsSdk/2 NewsArticle/1.6.2 GoldBrowser/1.6.2 NetType/wifi TTWebView/0881130043405"
            user_agents = parse(user_agent)
            # browser
            browser = user_agents.browser.family
            browser_version = user_agents.browser.version_string

            # os
            os = user_agents.os.family
            os_version = user_agents.os.version_string

            #device
            brand = user_agents.device.brand
            model = user_agents.device.model

            print(os,os_version,browser,browser_version,brand,model)

if __name__ == '__main__':
    main()

`

output : Android 11 Chrome Mobile WebView 88.0.4324 Oppo PCHM10

**Comment by caotao94** [comment]
And "zebra/21310 Mozilla/5.0 (iPad mini 5th generation; CPU OS 14_7_1 like Mac OS X; ZEBRA_APP_STORE) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148" cant input correct device info

**Comment by nielsbasjes** [comment]
I'm looking into the Oppo device but it seems like they have made a mess of their device ids.
Unsure how to handle that.

Regarding the `zebra/21310`, what is that? If I google `zebra/21310` I only find a `Zebra 21310 Orbitz Retractable Ballpoint Pen`. Right now it looks like a manually manipulated random string.

**Comment by nielsbasjes** [comment]
I think I found the source of this: https://getzbra.com/
`A modern, fast, and powerful open-source package manager for jailbroken iOS devices.`
https://github.com/zbrateam/Zebra

**Comment by caotao94** [comment]
yes，I think it is jailbroken device

**Comment by nielsbasjes** [comment]
I have fixed the zebra case: https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Apple.yaml#L1804

I have chosen **not** to fix the Oppo case because of that I have already documented here: https://yauaa.basjes.nl/expect/limitations/#device-name-and-device-brand
I check the Oppo device tags and they are really without any sensible pattern AND they overlap with other brands.
I have made some modifications that now allow you to extend the list of detected device tags yourself. In this file I used your example to ensure the extending works:
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/test/resources/LookupMergingOppo.yaml#L33
