### ISSUE TITLE
garbage chars into results

### ISSUE THREAD

**Issue by eriknyk** [nielsbasjes/yauaa#85]
I'm getting garbage chars in my results:
something like: `>` and `#20<"`, etc

![image](https://user-images.githubusercontent.com/205721/40688634-6c082898-6364-11e8-8f93-6e552dca1603.png)

Any idea?
Best Regards.

**Comment by nielsbasjes** [comment]
What your development tool shows here is the output of the default toString() method. 
Since the AgentField has both a value and a confidence I have chosen to implement the toString of the AgentField to show both of them in this form.

https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/java/nl/basjes/parse/useragent/UserAgent.java#L268

    @Override
    public String toString() {
        return ">" + this.value + "#" + this.confidence + "<";
    }


So this is not garbage, this is how it was intended.
